import { createRow, initSchema, pool, truncateTables, type EntityName } from "./db.ts";

const data: Record<EntityName, Record<string, unknown>[]> = {
  regions: [
    {
      name: "东大陆中部",
      continent: "东大陆",
      climate: "气候温和，河流、草场、林地和曜石资源较多。",
      terrain: "河谷、草场、林地、旧祭地、曜石浅脉。",
      dangerLevel: 3,
      mapX: 58,
      mapY: 48,
      mapZoom: 1.2,
      description: "赤牙、鹿角、石集、青陶、雷鼓、长弓等强部落围绕这里争夺秩序。"
    },
    {
      name: "东大陆西部沙漠",
      continent: "东大陆",
      climate: "干旱、沙暴频繁，昼夜温差极大。",
      terrain: "沙丘、荒原、绿洲、古海盆地、跨海口。",
      dangerLevel: 5,
      mapX: 18,
      mapY: 54,
      mapZoom: 1.6,
      description: "两大陆最可能联通的位置，也是铜影会扎根和封锁信息的区域。"
    },
    {
      name: "东大陆北部密林山地",
      continent: "东大陆",
      climate: "湿冷、多雾，寒岭风强。",
      terrain: "密林、大山、寒岭、河谷。",
      dangerLevel: 4,
      mapX: 28,
      mapY: 14,
      mapZoom: 1.5,
      description: "西北海岸与密林山地交错，近断鳞海路与西大陆，眠梦巡岸救起北回潮送来的婴儿，灰芽等旁支部落分散其间。"
    },
    {
      name: "东大陆南部水泽密林",
      continent: "东大陆",
      climate: "潮湿炎热，雨季漫长。",
      terrain: "水泽、沼地、藤林、蛇骨湿地。",
      dangerLevel: 4,
      mapX: 62,
      mapY: 73,
      mapZoom: 1.4,
      description: "泽蛙、百藤、蛇骨、蚌母等部落活跃，密林防御与水路生存强。"
    },
    {
      name: "西大陆东岸",
      continent: "西大陆",
      climate: "海风强烈，潮汐异常。",
      terrain: "断崖、礁湾、听潮旧岸、铜日登陆点。",
      dangerLevel: 5,
      mapX: -26,
      mapY: 50,
      mapZoom: 1.3,
      description: "听潮部落旧地，铜日诸部从这里打开跨海征服的方向。"
    },
    {
      name: "断鳞海路",
      continent: "两大陆之间",
      climate: "怪风、迷雾、暴流交替出现。",
      terrain: "暗礁、暴流、雾海、巨兽活动带。",
      dangerLevel: 5,
      mapX: -5,
      mapY: 51,
      mapZoom: 1.8,
      description: "隔绝东、西大陆的危险海路，只有极少数船只和潮汐异象能穿过。"
    },
    {
      name: "古海盆地",
      continent: "东大陆",
      climate: "干冷、风沙重，地下仍有旧水脉。",
      terrain: "干涸海床、王兽沉睡槽、王级曜石矿脉。",
      dangerLevel: 5,
      mapX: 25,
      mapY: 59,
      mapZoom: 1.7,
      description: "黑脊地龙王最终被引导重新沉睡的地方，也是王级曜石封禁区。"
    }
  ],
  tribes: [
    {
      name: "灰芽部落",
      continent: "东大陆",
      region: "东大陆北部密林山地",
      factionType: "支属",
      totem: "青蹄鹿",
      totemOrigin: "救命之恩",
      hearthName: "灰芽支火",
      hearthState: "稳定",
      strengthLevel: 2,
      population: 180,
      specialties: "草药、山林小猎、辨毒、雾中辨路、安抚幼兽。",
      preferences: "稳定水源、药草地、鹿角主火承认、避免卷入强部落战争。",
      taboos: "不可焚毁新芽，不可在无祭祀时猎杀幼鹿。",
      abilities: "弱治疗、辨草药、雾中不易迷路。",
      weakness: "武力不足，受鹿角主部落资源集中政策影响大。",
      stance: "保护青岚，前期回避大部落政治，是主角成长根系。",
      coordinatesX: 36,
      coordinatesY: 16,
      description: "鹿角旁支小部落，主角青岚成长之地。西北河口低地，海风可至，与眠梦部落有旧交。普通族人不知道他的海上来历。"
    },
    {
      name: "鹿角主部落",
      continent: "东大陆",
      region: "东大陆中部",
      factionType: "部落",
      totem: "白角鹿",
      totemOrigin: "救命之恩",
      hearthName: "白角主火",
      hearthState: "稳定",
      strengthLevel: 4,
      population: 1700,
      specialties: "治疗、草药、驯养、种植、支属协调。",
      preferences: "药草地、稳定支火、盟约、避免无谓战争。",
      taboos: "不可强行抹除支图腾，不可污染药泉。",
      abilities: "治疗、植物感知、安抚野兽、支火共鸣。",
      weakness: "正面战力不如赤牙，支属压力容易引发内部裂痕。",
      stance: "在赤牙压力下集中资源，前期容易被青岚误解。",
      coordinatesX: 46,
      coordinatesY: 28,
      description: "灰芽的主部落，主火和支火共同维持鹿角体系。"
    },
    {
      name: "赤牙部落",
      continent: "东大陆",
      region: "东大陆中部",
      factionType: "部落",
      totem: "焰牙虎",
      totemOrigin: "恐惧转敬畏",
      hearthName: "焰牙主火",
      hearthState: "强盛",
      strengthLevel: 5,
      population: 2600,
      specialties: "近战、狩猎、战争动员、并火、猎王准备。",
      preferences: "高级曜石、战士、盐、药草、猎王情报。",
      taboos: "不可怯战，不可背弃战誓。",
      abilities: "激发战士狂性、强化筋骨、短暂免痛。",
      weakness: "好战导致火浊风险，猎王路线会破坏地脉平衡。",
      stance: "明面压力，试图猎杀黑脊地龙王以整合东大陆。",
      coordinatesX: 44,
      coordinatesY: 40,
      description: "第一部明面强敌之一。不是单纯反派，而是把真实恐惧导向强行统一。"
    },
    {
      name: "石集诸部",
      continent: "东大陆",
      region: "东大陆中部",
      factionType: "部落联盟",
      totem: "双面契骨",
      totemOrigin: "祖先契约",
      hearthName: "契骨火垒",
      hearthState: "稳定",
      strengthLevel: 4,
      population: 2100,
      specialties: "贸易、契约、辨伪、曜石流通、弱部落抱团。",
      preferences: "稳定秩序、货路安全、灵纹骨、低冲突。",
      taboos: "不可破坏火垒契约，不可伪造巫印。",
      abilities: "契约辨伪、语言沟通、记忆交换。",
      weakness: "军事力量一般，必须平衡强部落。",
      stance: "关键中立贸易方，后期可切断铜影会债务网络。",
      coordinatesX: 54,
      coordinatesY: 41,
      description: "东大陆最大的商品集散与契约部落群之一。"
    },
    {
      name: "云箕部落",
      continent: "东大陆",
      region: "东大陆西部沙漠",
      factionType: "部落",
      totem: "衔云鹿",
      totemOrigin: "共同生活",
      hearthName: "云箕雨火",
      hearthState: "衰弱",
      strengthLevel: 3,
      population: 760,
      specialties: "求雨、季风山口、水渠维护、雨季预兆。",
      preferences: "净水、云纹骨、季风、巫徒安全。",
      taboos: "不可锁水为私产，不可在旱季欺骗求雨。",
      abilities: "引云、辨雨、雾气感知、水脉异常感知。",
      weakness: "求雨失败率升高，被铜影会盯上水脉。",
      stance: "派巫徒外出寻找水脉异常原因，引出沙漠线。",
      coordinatesX: 24,
      coordinatesY: 53,
      description: "沙漠东缘部落，箕雨出身之地。"
    },
    {
      name: "听潮部落",
      continent: "西大陆",
      region: "西大陆东岸",
      factionType: "部落",
      totem: "海潮",
      totemOrigin: "祖先契约",
      hearthName: "听潮火塘",
      hearthState: "归海",
      strengthLevel: 4,
      population: 0,
      specialties: "听海风、辨海路、守海峡、潮纹礼器。",
      preferences: "尊海、守岸、不征服海。",
      taboos: "不可主动跨海征服，不可为铜日诸部导航。",
      abilities: "从海风捕捉信息、潮声预兆、守门血誓。",
      weakness: "宁折不弯，被铜日诸部灭族。",
      stance: "主角阿澜出生部落，旧火归海，余火藏入阿澜与潮门青坠。",
      coordinatesX: -24,
      coordinatesY: 49,
      description: "主角阿澜的出生部落。灭族后火种不是被水浇灭，而是归海。"
    },
    {
      name: "眠梦部落",
      continent: "东大陆",
      region: "东大陆北部密林山地",
      factionType: "部落",
      totem: "眠果与梦蛾",
      totemOrigin: "共同生活",
      hearthName: "眠梦火塘",
      hearthState: "稳定",
      strengthLevel: 2,
      population: 360,
      specialties: "入梦、预兆、梦蛾茧、记忆碎片。",
      preferences: "安静林地、梦蛾、祭梦灰、保守秘密。",
      taboos: "不可滥用梦蛾粉，不可公开未定之梦。",
      abilities: "梦境预言、记忆触发、灾难碎片感知。",
      weakness: "人口少，完整知情者极少，容易被大部落利用。",
      stance: "救起海上婴儿，将潮门青坠交给赤牙巫并秘密托孤。",
      coordinatesX: 28,
      coordinatesY: 16,
      description: "第一幕关键部落，驻西北听潮旧岸附近巡岸，近西大陆与断鳞海路，梦见西大陆奴役文明跨海而来的灾难，救起北回潮送来的海上婴儿。"
    },
    {
      name: "雷鼓部落",
      continent: "东大陆",
      region: "东大陆中部",
      factionType: "部落",
      totem: "雷鼓兽",
      totemOrigin: "恐惧转敬畏",
      hearthName: "雷鼓战火",
      hearthState: "强盛",
      strengthLevel: 4,
      population: 1900,
      specialties: "草原重装、阵列、冲阵、战鼓威慑。",
      preferences: "威望、盟誓位置、战利品分配。",
      taboos: "不可怯阵，不可弃鼓逃散。",
      abilities: "战鼓共振、冲阵强体、压迫敌方阵线。",
      weakness: "重威望，容易被赤牙拉拢或激怒。",
      stance: "强部落博弈中的重要正面战力。",
      coordinatesX: 70,
      coordinatesY: 49,
      description: "清缴环城时负责正面压阵。"
    },
    {
      name: "长弓部落",
      continent: "东大陆",
      region: "东大陆中部",
      factionType: "部落",
      totem: "山鹰长弓",
      totemOrigin: "共同生活",
      hearthName: "长弓山火",
      hearthState: "稳定",
      strengthLevel: 4,
      population: 1300,
      specialties: "山地远射、通道控制、远程威慑。",
      preferences: "山道、猎场、箭木、通行权。",
      taboos: "不可无故断猎路，不可射杀盟誓使者。",
      abilities: "远视、稳弓、山风判断、封锁通道。",
      weakness: "不擅长持久正面冲阵。",
      stance: "可封锁环城山道和商路。",
      coordinatesX: 74,
      coordinatesY: 32,
      description: "强部落之一，赤牙试图拉拢或压服的对象。"
    },
    {
      name: "青陶部落",
      continent: "东大陆",
      region: "东大陆中部",
      factionType: "部落",
      totem: "青陶窑火",
      totemOrigin: "共同生活",
      hearthName: "青陶窑火",
      hearthState: "稳定",
      strengthLevel: 4,
      population: 1800,
      specialties: "储粮、陶器、建筑、防御工事、封井陶器。",
      preferences: "定居水土、陶土、粮仓安全。",
      taboos: "不可污染陶土，不可焚毁共粮窑。",
      abilities: "筑墙、封井、储粮防腐、陶纹记事。",
      weakness: "迁徙能力弱，受水源和土地限制。",
      stance: "清缴环城时提供储粮、封井陶器和临时防御。",
      coordinatesX: 52,
      coordinatesY: 61,
      description: "代表定居、工艺和防御秩序的强部落。"
    },
    {
      name: "百藤部落",
      continent: "东大陆",
      region: "东大陆南部水泽密林",
      factionType: "部落",
      totem: "百藤",
      totemOrigin: "共同生活",
      hearthName: "百藤湿火",
      hearthState: "稳定",
      strengthLevel: 3,
      population: 900,
      specialties: "密林防御、陷阱、藤桥、毒藤。",
      preferences: "湿林、藤种、隐蔽猎场。",
      taboos: "不可乱砍老藤，不可烧毁藤桥。",
      abilities: "缠绕陷阱、林中隐蔽、藤索行动。",
      weakness: "离开密林后战力下降。",
      stance: "南部强势防御部落，联盟阻力之一。",
      coordinatesX: 58,
      coordinatesY: 77,
      description: "东大陆南部重要部落。"
    },
    {
      name: "霜骨部落",
      continent: "东大陆",
      region: "北境寒岭",
      factionType: "部落",
      totem: "霜骨",
      totemOrigin: "禁忌赎罪",
      hearthName: "霜骨寒火",
      hearthState: "沉默",
      strengthLevel: 4,
      population: 820,
      specialties: "寒地战斗、骨器、忍耐、南下预警。",
      preferences: "寒岭、骨盐、冬猎。",
      taboos: "不可浪费遗骨，不可轻易南下。",
      abilities: "抗寒、骨器强化、低温追踪。",
      weakness: "南下成本极高，火塘沉默风险。",
      stance: "若霜骨南下，意味着大灾将至。",
      coordinatesX: 78,
      coordinatesY: 9,
      description: "北境寒地强部落。"
    },
    {
      name: "黑羽部落",
      continent: "东大陆",
      region: "东大陆南部水泽密林",
      factionType: "部落",
      totem: "黑羽鸦",
      totemOrigin: "祖先契约",
      hearthName: "黑羽告火",
      hearthState: "衰弱",
      strengthLevel: 2,
      population: 520,
      specialties: "凶兆、尸场辨认、远讯羽饰。",
      preferences: "旧战场、告死仪式、黑羽信物。",
      taboos: "不可嘲笑凶兆，不可夺死者羽饰。",
      abilities: "预感灾祸、辨尸、传递警讯。",
      weakness: "容易被其他部落视为不祥。",
      stance: "赤牙异常阶段传出不祥预兆。",
      coordinatesX: 48,
      coordinatesY: 74,
      description: "负责制造前期灾难阴影的部落，栖于南部密林旧战场与告死林地。"
    },
    {
      name: "玉部落",
      continent: "东大陆",
      region: "东大陆中部",
      factionType: "部落",
      totem: "玉石",
      totemOrigin: "共同生活",
      hearthName: "玉光火塘",
      hearthState: "稳定",
      strengthLevel: 3,
      population: 700,
      specialties: "玉器、礼器、盟誓信物、审美与身份标记。",
      preferences: "玉脉、礼器交换、婚盟。",
      taboos: "不可以裂玉作假誓。",
      abilities: "礼器稳定盟誓、安抚冲突。",
      weakness: "武力一般，依赖贸易和礼仪地位。",
      stance: "非兽形图腾体系的重要例子。",
      coordinatesX: 64,
      coordinatesY: 35,
      description: "大纲中用于扩展图腾来源的部落。"
    },
    {
      name: "砺石部落",
      continent: "东大陆",
      region: "东大陆中部",
      factionType: "部落",
      totem: "磨石",
      totemOrigin: "共同生活",
      hearthName: "砺石火塘",
      hearthState: "稳定",
      strengthLevel: 3,
      population: 680,
      specialties: "磨制石器、修刃、工具维护。",
      preferences: "好石料、工艺交换、稳定集市。",
      taboos: "不可拿祭石磨血债之刃。",
      abilities: "强化工具、辨石、修复武器。",
      weakness: "被强部落争夺工匠。",
      stance: "补足东大陆工艺体系。",
      coordinatesX: 61,
      coordinatesY: 37,
      description: "工艺型图腾部落。"
    },
    {
      name: "黑石部落",
      continent: "东大陆",
      region: "东大陆中部",
      factionType: "部落",
      totem: "黑石界碑",
      totemOrigin: "祖先契约",
      hearthName: "黑石界火",
      hearthState: "稳定",
      strengthLevel: 3,
      population: 720,
      specialties: "界碑、边界、冲突调停、守路。",
      preferences: "边界稳定、道路安全、界碑祭。",
      taboos: "不可挪动界碑，不可伪称旧界。",
      abilities: "辨界、守路、界碑誓约。",
      weakness: "夹在强部落之间时压力极大。",
      stance: "体现边界和盟约主题。",
      coordinatesX: 50,
      coordinatesY: 11,
      description: "地缘与秩序型部落。"
    },
    {
      name: "深窟部落",
      continent: "东大陆",
      region: "东大陆南部水泽密林",
      factionType: "部落",
      totem: "地下洞网",
      totemOrigin: "祖先契约",
      hearthName: "深窟暗火",
      hearthState: "沉默",
      strengthLevel: 3,
      population: 560,
      specialties: "洞穴生存、地下水、矿脉路径。",
      preferences: "洞网安全、无光菌、地下水。",
      taboos: "不可堵死祖洞，不可在暗火旁高喊。",
      abilities: "黑暗辨路、地下回声、矿脉嗅探。",
      weakness: "地表作战弱，封洞会重创部落。",
      stance: "补足地下地理与曜石来源。",
      coordinatesX: 44,
      coordinatesY: 79,
      description: "南部密林下的地下洞网部落，暗火与地下水脉交织。"
    },
    {
      name: "盐泽部落",
      continent: "东大陆",
      region: "东大陆南部水泽密林",
      factionType: "部落",
      totem: "盐泽",
      totemOrigin: "共同生活",
      hearthName: "盐泽白火",
      hearthState: "稳定",
      strengthLevel: 3,
      population: 650,
      specialties: "盐、腌制、防腐、泽地通行。",
      preferences: "盐池、交换、泽路安全。",
      taboos: "不可污染盐池。",
      abilities: "辨盐、保存粮肉、泽地耐性。",
      weakness: "盐池被占会失去根基。",
      stance: "资源型部落，战争时期非常关键。",
      coordinatesX: 63,
      coordinatesY: 71,
      description: "大纲中的南部资源部落。"
    },
    {
      name: "泽蛙部落",
      continent: "东大陆",
      region: "东大陆南部水泽密林",
      factionType: "部落",
      totem: "泽蛙",
      totemOrigin: "共同生活",
      hearthName: "泽蛙湿火",
      hearthState: "稳定",
      strengthLevel: 2,
      population: 520,
      specialties: "沼地行动、毒液、两栖狩猎。",
      preferences: "雨季、蛙鸣水塘、湿地猎场。",
      taboos: "不可在祭蛙季断水。",
      abilities: "沼地跳跃、毒感、湿地伪装。",
      weakness: "干旱季衰弱。",
      stance: "南部生态部落。",
      coordinatesX: 69,
      coordinatesY: 76,
      description: "水泽部落之一。"
    },
    {
      name: "蛇骨部落",
      continent: "东大陆",
      region: "东大陆南部水泽密林",
      factionType: "部落",
      totem: "蛇骨",
      totemOrigin: "禁忌赎罪",
      hearthName: "蛇骨冷火",
      hearthState: "稳定",
      strengthLevel: 3,
      population: 610,
      specialties: "毒、骨饰、蜿蜒通道、禁忌祭。",
      preferences: "蛇蜕、骨粉、隐秘沼道。",
      taboos: "不可随意折断祭蛇骨。",
      abilities: "毒抗、绕行、骨毒巫术。",
      weakness: "被外族忌惮，盟约难建立。",
      stance: "南部复杂势力之一。",
      coordinatesX: 76,
      coordinatesY: 79,
      description: "异质感较强的南部部落。"
    }
  ],
  characters: [
    {
      name: "青岚 / 阿澜",
      role: "主角、听潮首领之子、灰芽入火养子",
      tribeName: "灰芽部落 / 听潮部落",
      status: "成长中",
      secretLevel: 5,
      ability: "听界：感知火塘、人、契约、图腾、王兽和两大陆之间的边界裂缝。",
      knowledge: "前期不知身世；后期由潮门青坠、归海余火和旧祭词唤回阿澜之名。",
      motivation: "从寻找自己是谁，走向阻止奴役成为文明基石。",
      description: "他不是巫，不能替代祭祀。他的力量在于听见边界裂缝并推动选择。"
    },
    {
      name: "箕雨",
      role: "云箕巫徒",
      tribeName: "云箕部落",
      status: "外出寻因",
      secretLevel: 2,
      ability: "辨雨、感知苦水、云纹骨读兆。",
      knowledge: "知道云箕求雨失败率异常升高，听过环城传闻。",
      motivation: "找回季风断脉原因，保护云箕火塘。",
      description: "中期与青岚相遇，把沙漠大型聚集点第一次带入主角视野。"
    },
    {
      name: "眠梦主巫",
      role: "巫",
      tribeName: "眠梦部落",
      status: "守密者",
      secretLevel: 5,
      ability: "梦境预兆、记忆碎片触发、灾难梦。",
      knowledge: "知道孩子来自海上，见过潮门青坠，梦见东大陆火塘熄灭。",
      motivation: "隐藏青岚，避免他被梦境能力暴露。",
      description: "第一幕关键知情者之一。"
    },
    {
      name: "赤牙主巫",
      role: "巫",
      tribeName: "赤牙部落",
      status: "掌握核心秘密",
      secretLevel: 5,
      ability: "战巫、火塘灰辨兆、压火铜感知。",
      knowledge: "知道潮门青坠、海上婴儿、眠梦预言和沙漠商队部分真相。",
      motivation: "用猎王换取东大陆抵抗奴役文明的机会。",
      description: "复杂角色，清楚自己在纵容恐惧，却认为这是争取活路。"
    },
    {
      name: "赤牙首领",
      role: "战争领袖",
      tribeName: "赤牙部落",
      status: "推动猎王",
      secretLevel: 5,
      ability: "战争动员、近战威望、并火压服。",
      knowledge: "知道海那边真实存在另一片大陆，也知道东大陆分散将被吞掉。",
      motivation: "以战争整合东大陆，建立足以抵抗铜日诸部的主火。",
      description: "并非单纯贪婪，而是选择用强权回应未来灾难。"
    },
    {
      name: "铜影会首领",
      role: "奴隶主集团领袖",
      tribeName: "铜影会",
      status: "暗处经营环城",
      secretLevel: 4,
      ability: "债务控制、血铜器使用、信息封锁。",
      knowledge: "知道西大陆与东大陆之间的跨海口和信息差价值。",
      motivation: "利用东大陆战争建立自己的奴隶城邦。",
      description: "不忠于铜日诸部，也不属于东大陆，只忠于自己的奴役秩序。"
    }
  ],
  settlements: [
    {
      name: "灰芽火塘地",
      region: "东大陆北部密林山地",
      owner: "灰芽部落",
      settlementType: "支火聚落",
      population: 180,
      fireStatus: "稳定",
      tradeGoods: "草药、兽皮、山菌、鹿角片。",
      mapX: 50,
      mapY: 22,
      description: "青岚成长地，位于北部山林边缘。"
    },
    {
      name: "鹿角主火地",
      region: "东大陆中部",
      owner: "鹿角主部落",
      settlementType: "主火聚落",
      population: 1700,
      fireStatus: "稳定",
      tradeGoods: "草药、种子、治疗巫徒、驯养兽。",
      mapX: 46,
      mapY: 28,
      description: "鹿角体系主火所在，统合多个支属。"
    },
    {
      name: "环城",
      region: "东大陆西部沙漠",
      owner: "铜影会",
      settlementType: "沙漠聚集点",
      population: 4800,
      fireStatus: "无火",
      tradeGoods: "粮食、盐、奴仆、沙铜饰物、战争债务。",
      mapX: 18,
      mapY: 55,
      description: "表面是集市，地下是奴役与债务网络。"
    },
    {
      name: "云箕雨台",
      region: "东大陆西部沙漠",
      owner: "云箕部落",
      settlementType: "祭雨地",
      population: 240,
      fireStatus: "衰弱",
      tradeGoods: "净水、云纹骨、雨祭灰。",
      mapX: 28,
      mapY: 50,
      description: "云箕主巫不能离开的雨祭火塘。"
    },
    {
      name: "石集火垒",
      region: "东大陆中部",
      owner: "石集诸部",
      settlementType: "大型集市",
      population: 2100,
      fireStatus: "稳定",
      tradeGoods: "曜石、灵纹骨、陶器、盐、牲畜、契约信物。",
      mapX: 61,
      mapY: 44,
      description: "东大陆贸易和契约网络中心。"
    },
    {
      name: "听潮旧岸",
      region: "西大陆东岸",
      owner: "听潮部落",
      settlementType: "灭族旧地",
      population: 0,
      fireStatus: "归海",
      tradeGoods: "潮纹礼器、旧船木、盐火遗痕。",
      mapX: -24,
      mapY: 49,
      description: "听潮部落被灭后的旧岸，主角记忆回流之地。"
    },
    {
      name: "黑脊沉睡地",
      region: "古海盆地",
      owner: "无",
      settlementType: "王兽禁地",
      population: 0,
      fireStatus: "禁封",
      tradeGoods: "王级曜石矿脉、王兽遗骸传闻。",
      mapX: 31,
      mapY: 58,
      description: "黑脊地龙王沉睡和苏醒的地脉节点。"
    }
  ],
  resources: [
    {
      name: "曜石",
      category: "通用灵息结晶",
      grade: "低级至王级",
      region: "全大陆地脉、王兽活动区、古兽遗骸、旧祭地。",
      rarity: 4,
      useCase: "交易、祭祀、巫术材料、图腾战士强化。",
      risk: "无巫和火塘稳定时，吸收过量会导致兽化、疯癫或灵息反噬。",
      description: "只按纯度和稳定度分级，不按颜色或属性区分。"
    },
    {
      name: "低级曜石",
      category: "货币",
      grade: "低级曜石",
      region: "普通矿脉、旧祭地周边。",
      rarity: 2,
      useCase: "小额交易，普通族人也能持有。",
      risk: "纯度低，强化价值有限。",
      description: "部落间最常见的一般等价物。"
    },
    {
      name: "王级曜石",
      category: "战略资源",
      grade: "王级曜石",
      region: "王兽活动区、古老地脉节点、大型遗骸矿深处。",
      rarity: 5,
      useCase: "改变部落命运的大祭、强化与政治震慑。",
      risk: "争夺会引发战争，过度开采会扰动王兽和地脉。",
      description: "赤牙猎王路线追求的核心资源之一。"
    },
    {
      name: "青息芽",
      category: "草药 / 成人礼信物",
      grade: "普通至特异",
      region: "灰芽山林、溪谷、潮声异常地。",
      rarity: 3,
      useCase: "灰芽寻芽礼，感应火塘归属。",
      risk: "异常青息芽可能触发火塘与潮纹交叠。",
      description: "青岚成人礼中找到被海风吹弯的一片青息芽。"
    },
    {
      name: "沙铜",
      category: "西大陆铜器前兆",
      grade: "战略资源",
      region: "环城、铜影会商队、西部沙漠。",
      rarity: 4,
      useCase: "饰物、交易、武器、信息差证物。",
      risk: "让东大陆巫感到不适，并指向海那边的文明。",
      description: "赤牙巫从沙漠商队和潮门青坠之间完成拼图的关键线索。"
    },
    {
      name: "血铜器",
      category: "奴役器物",
      grade: "禁器",
      region: "西大陆、铜影会控制地。",
      rarity: 5,
      useCase: "奴印、锁火环、血铜鼓、压制图腾战士。",
      risk: "压低火塘回应，长期导致断火和能力扭曲。",
      description: "恐惧能喂养血铜器，却不能喂养图腾。"
    },
    {
      name: "压火铜",
      category: "血铜器前期认知名",
      grade: "禁器",
      region: "环城、铜影会水井、债务仪式。",
      rarity: 5,
      useCase: "压制火塘回应、控制水井、奴役关键人物。",
      risk: "会让巫感到火线被压。",
      description: "东大陆早期角色不应直接称其为血铜器，而称为压火铜或锁火铜。"
    },
    {
      name: "潮门青坠",
      category: "证物 / 遗物",
      grade: "特级信物",
      region: "听潮旧岸、眠梦部落、赤牙主巫手中。",
      rarity: 5,
      useCase: "证明海那边存在另一片大陆，触发主角记忆。",
      risk: "会暴露青岚身世，也可能被当成战争筹码。",
      description: "主角失忆后身上仅剩的信物，连接听潮灭族与东大陆预警。"
    },
    {
      name: "灵纹骨",
      category: "通信 / 巫术记录",
      grade: "贵重器物",
      region: "石集诸部、巫徒、正式使者。",
      rarity: 3,
      useCase: "记录口信、债务、预兆、巫印。",
      risk: "伪造会破坏契约信任。",
      description: "东大陆尚无成熟通用文字时的重要记号系统。"
    },
    {
      name: "火种",
      category: "共同体记忆",
      grade: "不可交易",
      region: "各部落火塘。",
      rarity: 5,
      useCase: "保存祖名、图腾之约和部落身份。",
      risk: "被强行并火会造成火浊、怨烟和巫梦污染。",
      description: "火种不是资源，不能像曜石一样简单堆叠。"
    }
  ],
  creatures: [
    {
      name: "黑脊地龙王",
      creatureType: "王兽",
      region: "古海盆地 / 东大陆中部地脉节点",
      isKingBeast: true,
      dangerLevel: 5,
      ability: "沉睡时加速曜石析出，苏醒时改变河道、震裂山谷、驱散兽群。",
      materialUse: "王级曜石矿脉、王兽遗骸、麟骨。",
      behavior: "地脉型王兽，周期将醒，正被过度开采与锁水污染扰动。",
      description: "赤牙想猎杀的王兽。它不是曜石唯一来源，而是这一代人够得着的最大富矿。"
    },
    {
      name: "梦蛾",
      creatureType: "异虫",
      region: "眠梦部落林地",
      isKingBeast: false,
      dangerLevel: 2,
      ability: "翅粉诱发梦境。",
      materialUse: "辅助眠梦巫预言。",
      behavior: "夜间聚集在火塘灰气附近，过量会损伤记忆。",
      description: "呼应记忆被洗去与找回的主题。"
    },
    {
      name: "裂甲牛",
      creatureType: "大型兽",
      region: "东大陆中部草场",
      isKingBeast: false,
      dangerLevel: 3,
      ability: "厚甲冲撞，适合共猎考验。",
      materialUse: "甲片、肉、筋、骨器。",
      behavior: "迁徙时容易被地脉震动影响。",
      description: "青岚成人礼后理解支属分工的重要共猎对象。"
    },
    {
      name: "梦果树",
      creatureType: "植物",
      region: "眠梦部落林地",
      isKingBeast: false,
      dangerLevel: 1,
      ability: "果实影响睡眠与梦境。",
      materialUse: "眠梦祭祀、入梦辅助。",
      behavior: "靠近火塘灰和梦蛾聚集地生长较好。",
      description: "眠梦部落图腾体系的一部分。"
    },
    {
      name: "白角鹿",
      creatureType: "图腾兽",
      region: "鹿角主部落周边林地",
      isKingBeast: false,
      dangerLevel: 2,
      ability: "引路、安抚、草药感知。",
      materialUse: "鹿角片、祭祀信物。",
      behavior: "不轻易接近外族，火塘强盛时更容易出现。",
      description: "鹿角主部落的主图腾显形。"
    },
    {
      name: "焰牙虎",
      creatureType: "图腾兽",
      region: "赤牙旧猎场",
      isKingBeast: false,
      dangerLevel: 4,
      ability: "勇猛、威慑、短暂免痛象征。",
      materialUse: "虎牙、战纹、祭歌。",
      behavior: "祖先恐惧转化为敬畏的图腾形象。",
      description: "赤牙部落图腾。"
    },
    {
      name: "雾肩鹿",
      creatureType: "支图腾兽",
      region: "鹿角支属山雾地",
      isKingBeast: false,
      dangerLevel: 2,
      ability: "迷踪、引雾、山雾引路。",
      materialUse: "雾鹿纹、支火祭。",
      behavior: "多出现在雾鹿支传承中。",
      description: "鹿角内部支图腾示例。"
    }
  ],
  factions: [
    {
      name: "铜影会",
      factionType: "奴隶主集团",
      origin: "听潮灭族后，西大陆逃亡奴隶主、边缘贵族、炉巫残党和血铜器持有者在东大陆沙漠结成。",
      publicFace: "沙漠商队、环城集市、戴环商人、雇佣武装。",
      hiddenGoal: "控制信息、贩卖战争、积累奴隶和曜石，同时阻止铜日诸部真正跨海。",
      resources: "压火铜、沙铜知识、债务网络、绿洲、奴仆。",
      weakness: "无东大陆火塘承认，血铜器有限且难以稳定重铸，曜石吸收易反噬。",
      description: "中期暗线势力。威胁像阴影和毒水，而不是无敌军团。"
    },
    {
      name: "铜日诸部",
      factionType: "部落联盟 / 王权雏形",
      origin: "西大陆强部落掌握青铜器并猎杀日鬃狮王后形成。",
      publicFace: "铜王、炉巫、铜甲战士、祭炉城。",
      hiddenGoal: "跨海征服、寻找曜石与新奴隶、建立奴隶社会秩序。",
      resources: "青铜器、血铜器、血铜冠、奴兵、早期文字与船只。",
      weakness: "旧图腾沉默、火浊、王兽残念侵蚀血铜冠。",
      description: "第一部结尾之后真正逼近的时代洪水。"
    },
    {
      name: "火环盟",
      factionType: "部落联盟",
      origin: "王兽危机与清缴环城后，东大陆各部推动建立的新秩序。",
      publicFace: "共火议会、战火首领、各部巫共同封禁曜石矿脉。",
      hiddenGoal: "让文明向前，但不以奴役作为基石。",
      resources: "盟誓、各部火塘、封禁矿脉、共同守护海岸口。",
      weakness: "联盟缓慢脆弱，需要处理旧怨、资源分配和合火边界。",
      description: "主角路线的制度化结果：环火成盟，而不是并火成王。"
    },
    {
      name: "赤牙猎王派",
      factionType: "战争派系",
      origin: "赤牙首领与赤牙主巫在确认西大陆威胁后推动。",
      publicFace: "猎王、并火、强征战士、统一东大陆。",
      hiddenGoal: "用王级曜石和王兽遗骸制造对抗奴役文明的力量。",
      resources: "赤牙战士、高级曜石、战争威望、战巫。",
      weakness: "猎王破坏地脉，强并火会制造火浊。",
      description: "赤牙路线：合理的恐惧，错误的解决方式。"
    }
  ],
  events: [
    {
      title: "眠梦灾梦",
      act: "前史 / 第一幕",
      region: "眠梦部落林地",
      eventType: "预言",
      visibleTo: "眠梦主巫，少数巫徒知道碎片。",
      hiddenTruth: "梦中出现跨海铜船、血铜鼓、奴印和东大陆火塘熄灭。",
      consequences: "眠梦主巫救下海上婴儿后意识到灾梦开始落地。",
      description: "第一部信息差的起点。"
    },
    {
      title: "听潮灭族",
      act: "前史",
      region: "西大陆东岸",
      eventType: "灭族 / 火种归海",
      visibleTo: "主角前期完全失忆，眠梦主巫与赤牙主巫只知碎片。",
      hiddenTruth: "听潮火塘没有被水浇灭，而是化为无焰盐火归海，余火藏入阿澜与潮门青坠。",
      consequences: "阿澜被北回潮送到东大陆北部，铜影会形成条件成熟。",
      description: "铜日诸部因听潮拒绝为远航征服导航而灭族。"
    },
    {
      title: "海上来的孩子",
      act: "第一幕",
      region: "东大陆海岸 / 眠梦部落",
      eventType: "救援 / 托孤",
      visibleTo: "眠梦主巫、极少数巫徒、赤牙主巫。",
      hiddenTruth: "孩子来自西大陆听潮部落，身上只剩潮门青坠。",
      consequences: "眠梦主巫将青岚托付给灰芽部落。",
      description: "主角进入东大陆火塘秩序。"
    },
    {
      title: "灰芽寻芽礼",
      act: "第二幕",
      region: "东大陆北部密林山地",
      eventType: "成人礼",
      visibleTo: "灰芽族人。",
      hiddenTruth: "青岚身上鹿角纹与潮纹交叠，说明灰芽火塘和归海余火都在回应他。",
      consequences: "青岚获得支属狩猎资格，开始进入部落生存压力。",
      description: "主角第一次表现出灰芽之感与听潮残响。"
    },
    {
      title: "裂甲牛共猎",
      act: "第二幕",
      region: "东大陆中部草场",
      eventType: "共猎",
      visibleTo: "灰芽与鹿角支属猎队。",
      hiddenTruth: "共猎分工预示支属体系不是单纯压迫。",
      consequences: "青岚理解支属之间的合作和主部落资源压力。",
      description: "前期成长事件。"
    },
    {
      title: "赤牙异常动员",
      act: "第三幕",
      region: "东大陆中部",
      eventType: "战争前兆",
      visibleTo: "各强部落。",
      hiddenTruth: "赤牙正为猎王与并火成王做准备。",
      consequences: "鹿角、石集、长弓、雷鼓等强部落开始博弈。",
      description: "明线压力开始浮出水面。"
    },
    {
      title: "箕雨外出寻因",
      act: "第四幕",
      region: "东大陆西部沙漠",
      eventType: "调查",
      visibleTo: "云箕部落、青岚。",
      hiddenTruth: "水脉异常与铜影会锁水、环城水井有关。",
      consequences: "青岚第一次听到环城传闻。",
      description: "把沙漠、苦水、铜影会外围影响带入主角视野。"
    },
    {
      title: "猎王真相浮现",
      act: "第五幕",
      region: "东大陆中部 / 黑脊沉睡地",
      eventType: "真相揭露",
      visibleTo: "青岚、赤牙、部分强部落。",
      hiddenTruth: "赤牙不是单纯扩张，而是恐惧西大陆奴役文明。",
      consequences: "青岚必须寻找第三条路。",
      description: "赤牙路线的合理性与错误同时显现。"
    },
    {
      title: "黑脊地龙王苏醒",
      act: "第六幕",
      region: "古海盆地",
      eventType: "王兽危机",
      visibleTo: "东大陆各部。",
      hiddenTruth: "过度开采、锁水污染和猎王准备共同扰动地脉。",
      consequences: "各部被迫合作，火环盟前身出现。",
      description: "主角证明不杀王兽也能渡过危机。"
    },
    {
      title: "清缴环城",
      act: "第七幕",
      region: "东大陆西部沙漠",
      eventType: "联合行动",
      visibleTo: "火环盟前身各部。",
      hiddenTruth: "环城不是普通集市，而是铜影会奴役和债务网络核心。",
      consequences: "铜影会被重创，东大陆第一次直面内部滋生的奴役。",
      description: "明线猎王之后的暗线爆发。"
    },
    {
      title: "火环盟誓",
      act: "第八幕",
      region: "古海盆地 / 共火议会",
      eventType: "盟誓 / 新制度",
      visibleTo: "东大陆各部落。",
      hiddenTruth: "火环盟不是国家，也不是王权，而是部落时代向更高文明的另一种可能。",
      consequences: "东大陆开始从松散部落时代走向联盟文明。",
      description: "主角路线制度化：各部保留火塘，在重大事务上环火成盟。"
    },
    {
      title: "西大陆反转",
      act: "第一部结尾",
      region: "断鳞海路 / 东大陆海岸",
      eventType: "终局反转",
      visibleTo: "青岚与火环盟核心人物。",
      hiddenTruth: "铜影会不是西大陆主力，真正的铜日诸部仍在海那边。",
      consequences: "第二部开启：铜日诸部真正开始跨海。",
      description: "赤牙当初的恐惧并非虚构，只是解决方式错了。"
    },
    {
      title: "潮门青坠记忆回流",
      act: "第一部结尾",
      region: "海边",
      eventType: "身份回归",
      visibleTo: "青岚。",
      hiddenTruth: "他不是被海放逐的人，而是被海送来的警告。",
      consequences: "阿澜之名回归，青岚同时背负两团火。",
      description: "主角身份线第一部收束。"
    }
  ]
};

await initSchema();
await truncateTables();

for (const [entity, rows] of Object.entries(data) as Array<[EntityName, Record<string, unknown>[]]>) {
  for (const row of rows) {
    await createRow(entity, row);
  }
}

await pool.end();

console.log("Seeded MySQL database from story-outline.md baseline");
